version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: real_estate_db_staging
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: real_estate_db_staging
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_staging:/var/lib/postgresql/data

volumes:
  postgres_data_staging:
